Catridges/Controllers/CatridgeController.cs
using Catridges.Domain.Entity;
using Catridges.Domain.Response;
using Catridges.Service.Interfases;
using Microsoft.AspNetCore.Mvc;

namespace Catridges.Controllers;

public class CatridgeController : Controller
{
    private readonly ICatridgeService _catridgeService;

    public CatridgeController(ICatridgeService catridgeService)
    {
        _catridgeService = catridgeService;
    }

    [HttpGet]
    public async Task<IActionResult> GetAllCatridges()
    {
        var response = await _catridgeService.ReadAll();
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return View(response.Data.ToList());
        }
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> GetCatridge(int id)
    {
        var response = await _catridgeService.Read(id);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return View(response.Data);
        }
        return View();
    }

    [HttpGet]
    public IActionResult CreateCatridge()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreateCatridge(string model)
    {
        var catridge = new Catridge() { Model = model };
        var response = await _catridgeService.Create(catridge);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return RedirectToAction("GetAllCatridges");
        }
        return View();
    }
    
    [HttpGet]
    public async Task<IActionResult> UpdateCatridge(int id)
    {
        var response = await _catridgeService.Read(id);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return View(response.Data);
        }
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> UpdateCatridge(int id, string model)
    {
        var catridge = new Catridge() { Model = model};
        var response = await _catridgeService.Update(id, catridge);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return RedirectToAction("GetAllCatridges");
        }
        return View();
    }
    
    [HttpGet]
    public async Task<IActionResult> DeleteCatridge(int id)
    {
        var response = await _catridgeService.Delete(id);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return RedirectToAction("GetAllCatridges");
        }
        return View();
    }
}

Catridges/Controllers/DocumentController.cs
using Catridges.Domain.Entity;
using Catridges.Domain.Response;
using Catridges.Domain.ViewModels;
using Catridges.Service.Interfases;
using Microsoft.AspNetCore.Mvc;

namespace Catridges.Controllers;

public class DocumentController : Controller
{
    private readonly IDocumentService _documentService;

    public DocumentController(IDocumentService documentService)
    {
        _documentService = documentService;
    }
    
    [HttpGet]
    public async Task<IActionResult> GetAllDocuments(string? searchString, string sortOrder)
    {
        ViewBag.NumberSortParam = string.IsNullOrEmpty(sortOrder) ? "number_desc" : "";
        var response = await _documentService.ReadAll(searchString, sortOrder);
        
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return View(response.Data.ToList());
        }
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> GetDocument(int id)
    {
        var response = await _documentService.Read(id);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return View(response.Data);
        }
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> CreateDocument()
    {
        var response = await _documentService.GetDocumentCreateViewModel();
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return View(response.Data);
        }
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreateDocument(int catridgeId, int printerId, int stateId, int subdivisionId,
        DateTime dateTime)
    {
        var documents = await _documentService.ReadAll(null,null);
        var documentview = await _documentService.GetDocumentCreateViewModel();
        int lastDocumentNumber = 0;
        if (documents.Data == null)
        {
            lastDocumentNumber = 1;
        }
        else
        {
            foreach (var item in documents.Data)
            {
                if (item.Number > lastDocumentNumber)
                {
                    lastDocumentNumber = item.Number;
                }
            }

            lastDocumentNumber++;
        }
        var document = new Document()
        {
            Catridge = documentview.Data.Catridges.FirstOrDefault(x=>x.Id == catridgeId) ,
            Printer = documentview.Data.Printers.FirstOrDefault(x=>x.Id == printerId),
            State = documentview.Data.States.FirstOrDefault(x=>x.Id == stateId),
            Subdivision = documentview.Data.Subdivisions.FirstOrDefault(x=>x.Id == subdivisionId),
            DateTime = dateTime,
            Number = lastDocumentNumber
            
        };
        var response = await _documentService.Create(document);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return RedirectToAction("GetAllDocuments");
        }
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> UpdateDocument(int id)
    {
        var document = await _documentService.Read(id);
        var response = await _documentService.GetDocumentCreateViewModel();
        if (document.StatusCode == Domain.Enum.StatusCode.OK)
        {
            ViewBag.Date = document.Data.DateTime;
            return View(response.Data);
        }

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> UpdateDocument(int id, int catridgeId, int printerId, int stateId, int subdivisionId,
        DateTime dateTime)
    {
        var documentview = await _documentService.GetDocumentCreateViewModel();
        var documentold = await _documentService.Read(id);
        var numberDocument = documentold.Data.Number;
        var document = new Document()
        {
            Catridge = documentview.Data.Catridges.FirstOrDefault(x=>x.Id == catridgeId),
            Printer = documentview.Data.Printers.FirstOrDefault(x=>x.Id == printerId),
            State = documentview.Data.States.FirstOrDefault(x=>x.Id == stateId),
            Subdivision = documentview.Data.Subdivisions.FirstOrDefault(x=>x.Id == subdivisionId),
            DateTime = dateTime,
            Number = numberDocument
            
        };
        var response = await _documentService.Update(id, document);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return RedirectToAction("GetAllDocuments");
        }

        return View();
    }

    [HttpGet]
    public async Task<IActionResult> DeleteDocument(int id)
    {
        var response = await _documentService.Delete(id);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return RedirectToAction("GetAllDocuments");
        }

        return View();
    }
}

Catridges/Controllers/PrinterController.cs
using Catridges.Domain.Entity;
using Catridges.Service.Interfases;
using Microsoft.AspNetCore.Mvc;

namespace Catridges.Controllers;

public class PrinterController : Controller
{
   private readonly IPrinterService _printerService;

    public PrinterController(IPrinterService printerService)
    {
        _printerService = printerService;
    }

    [HttpGet]
    public async Task<IActionResult> GetAllPrinters()
    {
        var response = await _printerService.ReadAll();
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return View(response.Data.ToList());
        }
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> GetPrinter(int id)
    {
        var response = await _printerService.Read(id);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return View(response.Data);
        }
        return View();
    }

    [HttpGet]
    public IActionResult CreatePrinter()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreatePrinter(string model)
    {
        var printer = new Printer() { Model = model };
        var response = await _printerService.Create(printer);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return RedirectToAction("GetAllPrinters");
        }
        return View();
    }
    
    [HttpGet]
    public async Task<IActionResult> UpdatePrinter(int id)
    {
        var response = await _printerService.Read(id);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return View(response.Data);
        }
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> UpdatePrinter(int id, string model)
    {
        var printer = new Printer() { Model = model};
        var response = await _printerService.Update(id, printer);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return RedirectToAction("GetAllPrinters");
        }
        return View();
    }
    
    [HttpGet]
    public async Task<IActionResult> DeletePrinter(int id)
    {
        var response = await _printerService.Delete(id);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return RedirectToAction("GetAllPrinters");
        }
        return View();
    }
}

Catridges/Controllers/StateController.cs
using Catridges.Domain.Entity;
using Catridges.Domain.Response;
using Catridges.Service.Interfases;
using Microsoft.AspNetCore.Mvc;

namespace Catridges.Controllers;

public class StateController : Controller
{
   private readonly IStateServise _stateServise;

   public StateController(IStateServise stateServise)
   {
      _stateServise = stateServise;
   }
   
   [HttpGet]
   public async Task<IActionResult> GetAllStates()
   {
      var response = await _stateServise.ReadAll();
      if (response.StatusCode == Domain.Enum.StatusCode.OK)
      {
         return View(response.Data.ToList());
      }

      return View();
   }
   
   [HttpGet]
   public async Task<IActionResult> GetState(int id)
   {
      var response = await _stateServise.Read(id);
      if (response.StatusCode == Domain.Enum.StatusCode.OK)
      {
         return View(response.Data);
      }
      return View();
   }
   
   [HttpGet]
   public IActionResult CreateState()
   {
      return View();
   }

   [HttpPost]
   public async Task<IActionResult> CreateState(string model)
   {
      var state = new State() { Name = model };
      var response = await _stateServise.Create(state);
      if (response.StatusCode == Domain.Enum.StatusCode.OK)
      {
         return RedirectToAction("GetAllStates");
      }
      return View();
   }
   
   [HttpGet]
   public async Task<IActionResult> UpdateState(int id)
   {
      var response = await _stateServise.Read(id);
      if (response.StatusCode == Domain.Enum.StatusCode.OK)
      {
         return View(response.Data);
      }
      return View();
   }
    
   [HttpPost]
   public async Task<IActionResult> UpdateState(int id, string model)
   {
      var state = new State() { Name = model};
      var response = await _stateServise.Update(id, state);
      if (response.StatusCode == Domain.Enum.StatusCode.OK)
      {
         return RedirectToAction("GetAllStates");
      }
      return View();
   }
    
   [HttpGet]
   public async Task<IActionResult> DeleteState(int id)
   {
      var response = await _stateServise.Delete(id);
      if (response.StatusCode == Domain.Enum.StatusCode.OK)
      {
         return RedirectToAction("GetAllStates");
      }
      return View();
   }
   
}

Catridges/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Управление катриджами</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link href="css/dashboard.css" rel="stylesheet">
    <link rel="stylesheet" href="css/site.css" asp-append-version="true"/>
</head>
<body>
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#">Управление катриджами</a>
    <button class="navbar-toggle position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggle-icon"></span>
    </button>
    <div class="form-control form-control-dark w-100 rounded-0 border-0">
       <form asp-action="GetAllDocuments" method="get">
           <input class="w-75" name="searchString" type="text" placeholder="Поиск" aria-label="Search">
           <input type="submit" value="Search" class="btn btn-dark"/>
       </form> 
    </div>
    <div class="navbar-nav">
        <div class="nav-item text-nowrap">
            <a class="nav-link px-3" href="#">Выход</a>
        </div>
    </div>
</header>

<div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-controller="Document" asp-action="GetAllDocuments">
                            <span data-feather="home" class="align-text-bottom"></span>
                            Главная
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file" class="align-text-bottom"></span>
                            Выход
                        </a>
                    </li>
                </ul>
      
                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
                    <span>Управление моделями</span>
                    <a class="link-secondary" href="#" aria-label="Add a new report">
                        <span data-feather="plus-circle" class="align-text-bottom"></span>
                    </a>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Catridge" asp-action="GetAllCatridges">
                            <span data-feather="file-text" class="align-text-bottom"></span>
                            Картриджи
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Printer" asp-action="GetAllPrinters">
                            <span data-feather="file-text" class="align-text-bottom"></span>
                            Принтеры
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="State" asp-action="GetAllStates">
                            <span data-feather="file-text" class="align-text-bottom"></span>
                            Статусы
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Subdivision" asp-action="GetAllSubdivisions">
                            <span data-feather="file-text" class="align-text-bottom"></span>
                            Подразделения
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
      
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            @RenderBody()
        </main>
    </div>
</div>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>