Catridges/Controllers/SubdivisionController.cs
using Catridges.Domain.Entity;
using Catridges.Service.Interfases;
using Microsoft.AspNetCore.Mvc;

namespace Catridges.Controllers;

public class SubdivisionController : Controller
{
    private readonly ISubdivisionService _subdivisionService;

    public SubdivisionController(ISubdivisionService subdivisionService)
    {
        _subdivisionService = subdivisionService;
    }
    
    [HttpGet]
    public async Task<IActionResult> GetAllSubdivisions()
    {
        var response = await _subdivisionService.ReadAll();
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return View(response.Data.ToList());
        }
    
        return View();
    }
       
    [HttpGet]
    public async Task<IActionResult> GetSubdivision(int id)
    {
        var response = await _subdivisionService.Read(id);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return View(response.Data);
        }
        return View();
    }
       
    [HttpGet]
    public IActionResult CreateSubdivision()
    {
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> CreateSubdivision(string model)
    {
        var subdivision = new Subdivision() { Name = model };
        var response = await _subdivisionService.Create(subdivision);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return RedirectToAction("GetAllSubdivisions");
        }
        return View();
    }
       
    [HttpGet]
    public async Task<IActionResult> UpdateSubdivision(int id)
    {
        var response = await _subdivisionService.Read(id);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return View(response.Data);
        }
        return View();
    }
        
    [HttpPost]
    public async Task<IActionResult> UpdateSubdivision(int id, string model)
    {
        var subdivision = new Subdivision() { Name = model};
        var response = await _subdivisionService.Update(id, subdivision);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return RedirectToAction("GetAllSubdivisions");
        }
        return View();
    }
        
    [HttpGet]
    public async Task<IActionResult> DeleteSubdivision(int id)
    {
        var response = await _subdivisionService.Delete(id);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return RedirectToAction("GetAllSubdivisions");
        }
        return View();
    }
}

Catridges/Views/Subdivision/CreateSubdivision.cshtml
@model bool

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<body>
<div>
    <br/>
    <h2>Подразделение.
        Создание нового подразделения.</h2>
    <br/>
</div>
<form method="post">
    <div class="mb-3">
        <label for="model" class="form-label fw-bold">Наименование подразделения</label>
        <input type="text" class="form-control form-control-dark" name="model" id="model">
    </div>
    <button type="submit" class="btn btn-dark text-white">Создать</button>
</form>
<br/>
<div>
    <a class="btn btn-dark text-white" asp-controller="Subdivision" asp-action="GetAllSubdivisions">Назад</a>
</div>
</body>

Catridges/Views/Subdivision/DeleteSubdivision.cshtml
@model bool

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<body>
<br/>
<h1 class="fw-bold">Sucsess</h1>
<br/>
<div style="position: center">
    <a class="btn btn-dark" asp-controller="Subdivision" asp-action="GetAllSubdivisions">Назад</a>
</div>
</body>

Catridges/Views/Subdivision/GetAllSubdivisions.cshtml
@model IEnumerable<Catridges.Domain.Entity.Subdivision>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<body>
<br/>
<h2>Подразделения.
    Модуль управления подразделениями.</h2>
<br/>
<div class="table-active">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th>#</th>
            <th>Наименование</th>
        </tr>
        </thead>
        <tbody>
        @{
            if (@Model != null)
            {
                int i = 1;
                foreach (var item in @Model)
                {
                    <tr>
                        <td width="40">@i</td>
                        <td width="*">@item.Name</td>
                        <td width="80"><a class="btn btn-outline-dark" asp-controller="Subdivision" asp-action="GetSubdivision" asp-route-id="@item.Id">Открыть</a></td>
                        <td width="80"><a class="btn btn-outline-dark" asp-controller="Subdivision" asp-action="UpdateSubdivision" asp-route-id="@item.Id">Изменить</a></td>
                        <td width="80"><a class="btn btn-outline-dark" asp-controller="Subdivision" asp-action="DeleteSubdivision" asp-route-id="@item.Id">Удалить</a></td>
                    </tr>
                    i++;
                } 
            }
        }
        </tbody>
    </table>
</div>
<div>
    <a class="btn btn-dark text-white text-center"  asp-controller="Subdivision" asp-action="CreateSubdivision">Добавить подразделение</a>
</div>

</body>

Catridges/Views/Subdivision/GetSubdivision.cshtml
@model Catridges.Domain.Entity.Subdivision

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<body>
<br/>
<h2>Подразделения.
    Просмотр подразделения @Model.Name.</h2>
<br/>
<div class="table-active">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Наименование</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td width="40">1</td>
            <td width="*">@Model.Name</td>
            <td width="80"><a class="btn btn-outline-dark" asp-controller="Subdivision" asp-action="UpdateSubdivision" asp-route-id="@Model.Id">Изменить</a></td>
            <td width="80"><a class="btn btn-outline-dark" asp-controller="Subdivision" asp-action="DeleteSubdivision" asp-route-id="@Model.Id">Удалить</a></td>
        </tr>
        </tbody>
    </table>
    <div style="position: center" >
        <a class="btn btn-dark"  asp-controller="Subdivision" asp-action="GetAllSubdivisions">Назад</a>
    </div>
</div>
</body>

Catridges/Views/Subdivision/UpdateSubdivision.cshtml
@model Catridges.Domain.Entity.Subdivision

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<body>
<div>
    <br/>
    <h2>Подразделения.
        Изменение подразделения @Model.Name.</h2>
    <br/>
</div>
<form method="post">
    <div class="mb-3">
        <label for="model" class="form-label fw-bold">Наименование подразделения</label>
        <input type="hidden" name="id" id="id" value="@Model.Id"/>
        <input type="text" class="form-control form-control-dark" name="model" id="model" value="@Model.Name">
    </div>
    <button type="submit" class="btn btn-dark text-white">Изменить</button>
</form>
<br/>
<div>
    <a class="btn btn-dark text-white" asp-controller="Subdivision" asp-action="GetAllSubdivisions">Назад</a>
</div>
</body>